### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by neuromancer** [metalvoidzz/Sourcehold#1]
I think people will be more interested in testing this reimplementation and maybe collaborate with some code if you show its current state with some screenshots (even early ones!).

**Comment by metalvoidzz** [comment]
Great idea! I'm currently working on a test build, including some early gameplay. I will add some screenshots and maybe a video when it's ready.

**Comment by neuromancer** [comment]
Neat!, I tested your code last night and it looks it works with Stronghold HD (GOG). You should include that in the README as well.
