### ISSUE TITLE
Other Stronghold reimplementations

### ISSUE THREAD

**Issue by neuromancer** [metalvoidzz/Sourcehold#4]
I don't know if you are aware, but there are other Stronghold re-implementations:

* https://github.com/fabian-arnold/stronghold-js
* https://github.com/leidav/CastlekeepNew

I wonder if there is something useful in that repositories or if the developers want to join forces with you.

**Comment by metalvoidzz** [comment]
Wow. All I was aware of when I started the project was https://github.com/Dwillnio/openStronghold, which hasn't been updated since 2017. If any of those developers are interested, I would love to collaborate.

**Comment by Lolasik011** [comment]
I think that these authors need to cooperate with the Unofficial patch. 
And then it will bring greater success ...
@Sh0wdown What do you think ?

**Comment by FilipJanitor** [comment]
Apologies for hijacking this thread but also please consider adding some project info/outline of goals for potential collaborators. This seems to be a pretty cool project and it would be great if it could get some traction but at the moment it is kind of hard to help with something :)

**Comment by metalvoidzz** [comment]
You're right, I will try to add some documentation. May need some time for that however, first open-source project and so on ;)
