### ISSUE TITLE
Need Help GM2 Converter

### ISSUE THREAD

**Issue by Gaaammmler** [metalvoidzz/Sourcehold#8]
Hello metalvoidzz,

i write a new GM2 Exporter/Importer for easier editing the Images in the files but i do something wrong when i load the ByteArray for the Images
 I complete to load the:
    File Header 
    Palette 
    Image offset list 
    Image sizes list 
    Image Headers 
    Images as ByteArray

As an example i have the anim_armourer.gm1 loaded, the first picture there is 760 bytes big, but the decoding is not working right, do i have there a big mistake, maybe u can help me?

Picture of my code for decoding the bytearray:
![help](https://user-images.githubusercontent.com/5760157/56514226-0e5a9400-6535-11e9-9e99-e3bc1dc67f57.jpg)

ImageHeader of the first imgfile in anim_armourer.gm1 
![help](https://user-images.githubusercontent.com/5760157/56514499-ba9c7a80-6535-11e9-8e1b-125ca4e2b800.jpg)

my decoded picture:
![help](https://user-images.githubusercontent.com/5760157/56514302-377b2480-6535-11e9-8cff-292b4694ced9.jpg)

**Comment by metalvoidzz** [comment]
When extracting the length from the token byte, you are bitshifting the value by 3 after masking out the other bits. I think that could be the error.

**Comment by Gaaammmler** [comment]
Hm, i changed it to the following but doesnt work too.
![help](https://user-images.githubusercontent.com/5760157/56520516-ea9f4a00-6544-11e9-993d-a95ce787e849.jpg)

Maybe u can write me what are the first 2-3 rows of tokens u get from the anim_armourer.gm1(i cant run ur project on windows i tried it over 2 hours :/),
 for me they are newline tokens is the following:
first loop:(the next 24 bytes in the array all 128)
byte:128
tokentype:4

I tested the Color output(its maybe wrong too, i need to check if c# handles byte diffrent than c++) and get the following(webside about TGX Color encoding: https://stronghold.fandom.com/wiki/TGX_file_format)
byte: 0b0001_1111_0000_0000(should be pure-blue:   00011111-00000000(1F00) (r0 g0 b255)))
color i get:
r:56
g:24
b:0

byte: 0b0000_0000_0111_1100(should be pure-red:    00000000-01111100(007C) (r255 g0 b0))
color i get:
r:56
g:24
b:0

byte: 0b1110_0000_0000_0011;(should be pure-green:  11100000-00000011(E003) (r0 g255 b0))
color i get:
r:192
g:0
b:24

**Comment by metalvoidzz** [comment]
Maybe try to log an error when the default case in the switch statement is hit. If so, the parsing should be the problem. If not, it could have something to do with endianess (my code assumes little endian...). I hope this helps. Also, can you tell me what the issue is on Windows? That sounds quite bad!

**Comment by Gaaammmler** [comment]
Ich habe gerade gesehen das du aus Deutschland kommst, es ist denke ich einfacher auf Deutsch weiter zu schreiben.

Also beim Parsen komme ich öfters in den default block also scheint da etwas nicht zu stimmen.

Mit den Farben habe ich mal eine test Methode gebaut zum swapen von den 2 Bytes(System gibt littleEndian = true an) mit folgenden Farben als Ausgabe:
![help](https://user-images.githubusercontent.com/5760157/56527586-2be82780-654e-11e9-90c4-0bf380c4e194.jpg)

0b0001_1111_0000_0000
R:0  G:0 B:248
-----------------------
0b0000_0000_0111_1100
R:248  G:0 B:0
-----------------------
0b1110_0000_0000_0011
R:0  G:31 B:0
-----------------------


Zu deinem Projekt:
Ich habe dein Projekt in Visual Studio mit der CMakeLists.txt geladen, nur weis ich nicht wie ich genau die thrid-party zusatz Dateien installieren muss ich habe diese jetzt in den Thridparty Ordner abgelegt und die CMakeLists bei den Verzeichnissen wie folgt verändert:(ich kenne mich leider nicht ganz sogut damit aus(neuland für mich))
# Find SDL2
include_directories(thirdparty/SDL/include/)

# Find OpenAL
include_directories(thirdparty/OpenAL/include/)

# Find FFMPEG
include_directories(thirdparty/ffmpeg/include/)


# Find swresample
include_directories(thirdparty/libavresample/include/)

# Find boost

set(Boost_USE_STATIC_LIBS ON) 
set(Boost_USE_MULTITHREADED ON)  
set(Boost_USE_STATIC_RUNTIME ON) 
include_directories(thirdparty/boost_1_70_0/include/)


![help](https://user-images.githubusercontent.com/5760157/56526969-42da4a00-654d-11e9-829d-e230261e53f2.jpg)

**Comment by metalvoidzz** [comment]
Ach ja, hätte mir bei dem Namen ja denken können, dass du Deutsch sprichst ;-). Die RGB Werte sollten eigentlich stimmen (ohne den Byteswap). Ansonsten könnte ich mir noch vorstellen, dass du beim Lesen der GM1 entries nicht zum offset aus der Liste springst. CMake sollte auch funktionieren, wenn man in der Commandline die `-DCMAKE_PREFIX_PATH=...` Option benutzt (muss ich mal zur README hinzufügen).

**Comment by Gaaammmler** [comment]
Ja war mir bei deinem zuerst nicht sicher hab es dan aber in GIT gesehen ;-) 

Welchen Offset meinst du genau, den von der Image offset list, der ist ja beim ersten bild 0 und das müsste soweit passen oder verstehe ich da etwas falsch?

Beim ersten Bild von der anim_armourer.gm1 Datei ist der offset ja 0 und bei der Image sizes list die zahl 760 hinterlegt

also ich lade ja erst den 88 byte header 
danach die 5,120 bytes Palette(die habe ich dan in Uint16 array von der größe 2560 umgewandelt) danach 16 mal den UInt32(4bytes) für den offset, 
dan 16 mal UInt32(4bytes) für die größe des arrays,
dan kommen die 16 ImgHeader mit jeweils 16 bytes,
und zum ende kommen 16 Images wo ich die größe und den offset aus den Listen zuvor entnehme und diese in die tgx dateien umwandle => und dabei klappt es gerade nicht.

Zum ende komme ich genau auf die größe der GM1 Datei, also müsste dort ja alles passen vom dekodieren.

**Comment by metalvoidzz** [comment]
Tut mir Leid, sonst fällt mir nichts ein. Viel Glück noch! (Btw, meine email ist metalvoidzz@gmail.com, falls dir noch etwas einfällt)
